spring:
  application:
    name: oar-dist-service
  profiles:
    active:
      local
  cloud:
    config:
      uri: http://localhost:8084   
      
server:
    port: 8083
    contextPath: /oar-dist-service
    error:
      include-stacktrace: never
    connection-timeout: 60000
    max-http-header-size: 8192
    tomcat:
      accesslog:
        directory: logs
        enabled: false
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8085/eureka/
        
security:
    headers:
      frame: true
      xss: true
      hsts: all
    enable-csrf: false