spring:
  application:
    name: oar-dist-service
  profiles:
    active:
      default
  cloud:
    config:
      uri: http://localhost:8888/oar-config-server       
      
server:
    port: 8080
    contextPath: /oar-dist-service
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/oar-discovery-server/